//8
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,E.SALARY FROM EMPLOYEES E 
WHERE E.DEPARTMENT_ID=(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='HR DEPARTMENT');

alter user myuser identified by mynewpassword account unlock;
select