CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID NUMBER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(50)UNIQUE NOT NULL,
LOCATION VARCHAR2(20) NOT NULL
);
DESC departments;
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY NUMERIC  NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);
DESC EMPLOYEES;
