CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)

CREATE TABLE PASSENGER(
PASS_ID NUMBER PRIMARY KEY  ,
FNAME VARCHAR(30) NOT NULL,
LNAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
AGE NUMBER NOT NULL,
CHECK(AGE<100)
);
 CREATE SEQUENCE user_id_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
--  (FNAME,LNAME,EMAIL,AGE)
CREATE OR REPLACE TRIGGER trg_PASSENGER_PASS_ID
  BEFORE INSERT ON PASSENGER
  FOR EACH ROW
BEGIN
  :new.PASS_ID := user_id_seq.nextval;
END;
  
  UPDATE PASSENGER
   SET PASS_ID = user_id_seq.nextval;
INSERT INTO PASSENGER VALUES (1,'SUNNY','BUNDA','SUNNY_BUNDA@HOTMAIL.COM',69);
INSERT INTO PASSENGER(FNAME,LNAME,EMAIL,AGE) VALUES ('SUNNY','BUNDA','SUYA_BUNDA@HOTMAIL.COM',88);
DESC PASSENGER;
SELECT * FROM PASSENGER;
DROP TABLE PASSENGER;
ALTER TABLE PASSENGER (AUTO_INCREMENT=100);

DROP TABLE PASSENGER