
Table DEPARTMENTS created.

Name            Null?    Type         
--------------- -------- ------------ 
DEPARTMENT_ID   NOT NULL NUMBER       
DEPARTMENT_NAME NOT NULL VARCHAR2(50) 
LOCATION        NOT NULL VARCHAR2(20) 

Error starting at line : 6 in command -
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)
Error report -
ORA-00905: missing keyword
00905. 00000 -  "missing keyword"
*Cause:    
*Action:

Error starting at line : 6 in command -
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)
Error report -
ORA-00905: missing keyword
00905. 00000 -  "missing keyword"
*Cause:    
*Action:

Error starting at line : 6 in command -
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)
Error report -
ORA-00905: missing keyword
00905. 00000 -  "missing keyword"
*Cause:    
*Action:

Error starting at line : 6 in command -
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)
Error report -
ORA-00905: missing keyword
00905. 00000 -  "missing keyword"
*Cause:    
*Action:

Error starting at line : 6 in command -
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)
Error report -
ORA-00905: missing keyword
00905. 00000 -  "missing keyword"
*Cause:    
*Action:

Error starting at line : 6 in command -
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER VARCHAR2(10) UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)
Error report -
ORA-00905: missing keyword
00905. 00000 -  "missing keyword"
*Cause:    
*Action:

Error starting at line : 6 in command -
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)
Error report -
ORA-00905: missing keyword
00905. 00000 -  "missing keyword"
*Cause:    
*Action:

Error starting at line : 3 in command -
CREATE TABLE EMPLOYEES(EMPLOYEE_ID NUMBER PRIMARY KEY,FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE ,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)
Error report -
ORA-00905: missing keyword
00905. 00000 -  "missing keyword"
*Cause:    
*Action:

Error starting at line : 7 in command -
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)
Error report -
ORA-00905: missing keyword
00905. 00000 -  "missing keyword"
*Cause:    
*Action:

Error starting at line : 7 in command -
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(30) NOT NULL,
EMAIL_ID VARCHAR2(60) UNIQUE NOT NULL,
PHONE_NUMBER NUMBER UNIQUE NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID NUMBER NOT NULL,
SALARY NUMERIC DOUBLE NOT NULL,
MANAGER_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);
Error report -
ORA-00907: missing right parenthesis
00907. 00000 -  "missing right parenthesis"
*Cause:    
*Action:

Table EMPLOYEES created.

Name          Null?    Type         
------------- -------- ------------ 
EMPLOYEE_ID   NOT NULL NUMBER       
FIRST_NAME    NOT NULL VARCHAR2(60) 
LAST_NAME     NOT NULL VARCHAR2(30) 
EMAIL_ID      NOT NULL VARCHAR2(60) 
PHONE_NUMBER  NOT NULL NUMBER       
HIRE_DATE     NOT NULL DATE         
JOB_ID        NOT NULL NUMBER       
SALARY        NOT NULL NUMBER       
MANAGER_ID             NUMBER       
DEPARTMENT_ID          NUMBER       
INSERT INTO DEPARTMENTS(101,'HR DEPARTMENT','BANGALORE');
INSERT INTO DEPARTMENTS(102,'IT DEPARTMENT','BANGALORE');
INSERT INTO DEPARTMENTS(103,'SUPPORT DEPARTMENT','CHENNAI');